### PR TITLE
Updated message dependencies, goal position dependencies

### PR DESCRIPTION
**Pull request by adamm08**
Replaced nav_channel::Task/TaskStatus/TaskGoalPosition with task_master::Task/TaskStatus/TaskGoalPosition.

Updated TaskGoalPosition to use floats for x, y, and z instead of PoseStamped message.

https://app.asana.com/0/1205704672457617/1205963318337969

### CODE REVIEW

**Review by gpearcey — COMMENTED** [review]
Need to figure out the the message types and make sure they line up.

**Comment by adamm08** [comment]
Removed the messages that were moved to task_master. Also changed the goal position and midpoints to use the Point message.

**Comment by adamm08** [comment]
Added the task number to when the taskGoalPosition publishes for the purposes of message filtering.

**Review by gpearcey — APPROVED** [review]

**Comment by gpearcey** [comment]
GTM

**Pull request merged**
